import json

# 根据之前读取的正确内容重建JSON
data = [
    ["【初始化】", "0", "print", "{}", "Y", "=== 采购数据处理 - PR/PO 差异化输出 ==="],
    ["【步骤1】选择源数据目录", "0", "print", "{}", "Y", "=== 请选择包含 purchase*.xlsx 文件的源数据目录 ==="],
    ["选择源数据目录", "10", "select_resource", '{"mode":"folder","title":"请选择包含Excel文件的源数据目录","save_to":"paths.source_dir","config_name":"elt_purchase_source_dir","config_note":"采购数据处理-源数据目录路径","use_cache":true,"force_refresh":false,"validate_exists":true}', "Y", "弹出窗口选择数据源目录(支持缓存)"],
    ["检查目录是否选择", "11", "condition", '{"check":"paths.get(\'source_dir\') == None","then":"选择源数据目录","else":"扫描目录文件"}', "Y", "如果取消则重新选择"],
    ["扫描目录文件", "12", "scan_directory", '{"folder_path":"${paths.source_dir}"}', "Y", "扫描目录中的所有文件"],
    ["打印扫描结果", "12a", "print_result", "{}", "Y", "调试用：显示扫描到的所有文件"],
    ["筛选purchase文件", "13", "filter_files", '{"conditions": [{"field": "modify_time", "operator": ">", "value": "-8640000"}, {"field": "size", "operator": ">", "value": "5"}, {"field": "size", "operator": "<", "value": "20480"}, {"field": "name", "operator": "~", "value": "purchase.+\\\\.xlsx$"}]}', "Y", "筛选：100天内修改、5KB-20MB、purchase*.xlsx"],
    ["打印筛选结果", "13a", "print_result", "{}", "Y", "调试用：显示筛选后的文件"],
    ["检查筛选结果", "14", "condition", '{"check":"len(last_result.get(\'items\', {})) == 0","then":"无文件处理","else":"合并Excel文件"}', "Y", "检查是否有匹配的文件"],
    ["合并Excel文件", "15", "merge_excel_files", '{"sheet":0,"header_row":1,"dedup_columns":[]}', "Y", "合并所有匹配的Excel文件"],
    ["保存合并数据", "16", "write_excel", '{"file":"${paths.output_dir}/merged_source.xlsx","sheet":"合并数据"}', "N", "可选：保存合并后的原始数据（调试）"],
    ["【步骤2】选择分工映射文件", "0", "print", "{}", "Y", "=== 请选择分工映射Excel文件 ==="],
    ["选择分工Excel", "20", "select_resource", '{"mode":"file","title":"请选择分工映射Excel文件","file_types":[["Excel文件","*.xlsx"],["所有文件","*.*"]],"save_to":"paths.mapping_file","config_name":"elt_purchase_mapping_file","config_note":"采购数据处理-分工映射Excel文件路径","use_cache":true,"force_refresh":false,"validate_exists":true}', "Y", "弹出窗口选择分工Excel(支持缓存)"],
    ["检查分工文件是否选择", "21", "condition", '{"check":"paths.get(\'mapping_file\') == None","then":"选择分工Excel","else":"选择输出目录"}', "Y", "如果取消则重新选择"],
    ["【步骤3】选择输出目录", "0", "print", "{}", "Y", "=== 请选择输出目录 ==="],
    ["选择输出目录", "30", "select_resource", '{"mode":"folder","title":"请选择数据输出目录","save_to":"paths.output_dir","config_name":"elt_purchase_output_dir","config_note":"采购数据处理-输出目录路径","use_cache":true,"force_refresh":false,"validate_exists":false}', "Y", "弹出窗口选择输出文件夹(支持缓存)"],
    ["检查输出目录是否选择", "31", "condition", '{"check":"paths.get(\'output_dir\') == None","then":"选择输出目录","else":"打印选择结果"}', "Y", "如果取消则重新选择"],
    ["【确认】", "0", "print", "{}", "Y", "========================================"],
    ["打印选择结果", "40", "print", "{}", "Y", "显示选择的路径信息"],
    ["【分组】数据准备阶段", "0", "print", "{}", "Y", "========================================"],
    ["加载物料组分工", "100", "read_excel", '{"file":"${paths.mapping_file}","sheet":"分工_物料组"}', "Y", "读取物料组映射-使用变量"],
    ["物料组分工筛选", "101", "select", '{"columns":["物料组","资源开发"]}', "Y", "保留映射列"],
    ["加载采购组分工", "102", "read_excel", '{"file":"${paths.mapping_file}","sheet":"分工_采购组"}', "Y", "读取采购组映射"],
    ["采购组分工筛选", "103", "select", '{"columns":["采购组","资源开发_采购组"]}', "Y", "保留映射列"],
    ["加载物料描述分工", "104", "read_excel", '{"file":"${paths.mapping_file}","sheet":"分工_物料描述_物料组"}', "Y", "读取物料描述模糊规则"],
    ["加载物料组采购组分工", "105", "read_excel", '{"file":"${paths.mapping_file}","sheet":"分工_物料组_采购组"}', "Y", "读取联合映射"],
    ["物料组采购组重命名", "106", "rename", '{"map":{"资源开发_物料组_采购组":"资源开发_物料组采购组"}}', "Y", "避免列名冲突"],
    ["物料组采购组选列", "107", "select", '{"columns":["物料组","采购组","资源开发_物料组采购组"]}', "Y", "保留映射列"],
    ["加载用户映射", "108", "read_excel", '{"file":"${paths.mapping_file}","sheet":"用户"}', "Y", "读取资源开发→用户映射"],
    ["用户映射筛选", "109", "select", '{"columns":["资源开发","用户"]}', "Y", "保留映射列"],
    ["【分组】加载主数据", "0", "print", "{}", "Y", "========================================"],
    ["加载采购申请数据", "200", "load_step_result", '{"step_id":"合并Excel文件"}', "Y", "加载合并后的Excel数据"],
    ["选择所需列", "201", "select", '{"columns":["请求项目","采购申请","短文本","物料","项目文本","申请数量","单位","工厂","采购组","物料组","申请者","已创建的","现有库存","需求日期","是否驳回","采购订单","PO日期","供应商名称"]}', "Y", "保留所需列（包含PR和PO的所有列）"],
    ["【分组】映射合并阶段", "0", "print", "{}", "Y", "========================================"],
    ["合并物料组映射", "300", "join", '{"source":"物料组分工筛选","on":"物料组","how":"left"}', "Y", "基础分工（优先级最低）"],
    ["合并物料组采购组映射", "301", "join", '{"source":"物料组采购组选列","on":["物料组","采购组"],"how":"left"}', "Y", "联合映射（优先级3）"],
    ["覆盖物料组采购组", "302", "overlay", '{"source_col":"资源开发_物料组采购组","target_col":"资源开发","drop":true}', "Y", "应用高优先级映射"],
    ["应用物料描述模糊匹配", "303", "fuzzy_override", '{"source":"加载物料描述分工","match_col":"物料组","text_col":"短文本","contains_col":"描述","source_val_col":"资源开发_物料描述_物料组","target_val_col":"资源开发"}', "Y", "模糊匹配（优先级2）"],
    ["合并采购组映射", "304", "join", '{"source":"采购组分工筛选","on":"采购组","how":"left"}', "Y", "采购组映射（优先级1）"],
    ["覆盖采购组", "305", "overlay", '{"source_col":"资源开发_采购组","target_col":"资源开发","drop":true}', "Y", "最高优先级覆盖"],
    ["合并用户映射", "306", "join", '{"source":"用户映射筛选","on":"资源开发","how":"left"}', "Y", "获取用户名"],
    ["【分组】计算处理阶段", "0", "print", "{}", "Y", "========================================"],
    ["格式化日期", "400", "calc", '{"new_col":"需求日期_dt","formula":"pd.to_datetime(需求日期.astype(str).str.strip(), format=\'%Y%m%d\', errors=\'coerce\')"}', "Y", "转换需求日期格式"],
    ["格式化PO日期", "401", "calc", '{"new_col":"PO日期_dt","formula":"pd.to_datetime(PO日期.astype(str).str.strip().str.replace(\'.\',\'/\',regex=False), format=\'%Y/%m/%d\', errors=\'coerce\')"}', "Y", "转换PO日期格式"],
    ["计算下单天数", "402", "calc", '{"new_col":"下单天数","formula":"pd.Series(pd.Timestamp(\'today\').normalize() - pd.to_datetime(np.where(采购订单.notna(), PO日期_dt, 需求日期_dt))).dt.days"}', "Y", "计算天数"],
    ["清理临时列", "403", "drop", '{"columns":["需求日期_dt","PO日期_dt"]}', "Y", "删除中间计算列"],
    ["按下单天数排序", "404", "sort", '{"column":"下单天数","ascending":true}', "Y", "升序排列"],
    ["【分组】输出阶段", "0", "print", "{}", "Y", "========================================"],
    ["输出全量数据", "500", "write_csv", '{"file":"${paths.output_dir}/all.csv","encoding":"gbk","clean_newlines":true}', "Y", "输出汇总结果"],
    ["重新加载全量", "500c", "load_step_result", '{"step_id":"输出全量数据"}', "Y", "重新加载数据"],
    ["筛选已转单", "501", "filter", '{"column":"采购订单","op":"notempty"}', "Y", "筛选已转单(采购订单非空)"],
    ["PO选择输出列", "501a", "select", '{"columns":["请求项目","采购申请","短文本","物料","项目文本","申请数量","单位","工厂","采购组","物料组","申请者","已创建的","现有库存","需求日期","采购订单","PO日期","供应商名称","资源开发","用户","下单天数"]}', "Y", "PO输出：去掉'是否驳回'列，保留供应商名称、PO日期、采购订单"],
    ["输出PO", "502", "write_csv", '{"file":"${paths.output_dir}/314.csv","encoding":"gbk"}', "Y", "输出已转单数据(带供应商名称、PO日期、采购订单，无是否驳回)"],
    ["拆分PO按人", "503", "split_write", '{"group_col":"资源开发","name_col":"用户","out_dir":"${paths.output_dir}/314","encoding":"gbk"}', "Y", "已转单按用户拆分"],
    ["加载全量快照", "504", "load_step_result", '{"step_id":"输出全量数据"}', "Y", "重新加载全量数据"],
    ["筛选未转单", "505", "filter", '{"column":"采购订单","op":"isempty"}', "Y", "筛选未转单(采购订单为空)"],
    ["PR选择输出列", "505a", "select", '{"columns":["请求项目","采购申请","短文本","物料","项目文本","申请数量","单位","工厂","采购组","物料组","申请者","已创建的","现有库存","需求日期","是否驳回","资源开发","用户","下单天数"]}', "Y", "PR输出：去掉'采购订单'、'PO日期'、'供应商名称'列，保留是否驳回"],
    ["输出PR", "506", "write_csv", '{"file":"${paths.output_dir}/313.csv","encoding":"gbk"}', "Y", "输出未转单数据(无采购订单、供应商名称、PO日期，带是否驳回)"],
    ["拆分PR按人", "507", "split_write", '{"group_col":"资源开发","name_col":"用户","out_dir":"${paths.output_dir}/313","encoding":"gbk"}', "Y", "未转单按用户拆分"],
    ["【分组】HTML可视化阶段", "0", "print", "{}", "Y", "========================================"],
    ["步骤说明", "0", "print", "{}", "Y", "=== 请选择HTML报告存放目录 ==="],
    ["选择HTML目录", "550", "select_resource", '{"mode":"folder","title":"请选择HTML报告存放目录","save_to":"paths.html_dir","config_name":"elt_purchase_html_dir","config_note":"采购数据处理-HTML报告存放目录","use_cache":true,"force_refresh":false,"validate_exists":false}', "Y", "选择HTML报告存放位置(支持缓存)"],
    ["检查HTML目录", "551", "condition", '{"check":"paths.get(\'html_dir\') == None","then":"选择HTML目录","else":"加载PO数据"}', "Y", "如果取消则重新选择"],
    ["加载PO数据", "560", "load_step_result", '{"step_id":"PO选择输出列"}', "Y", "加载已转单数据(已选择PO输出列)用于HTML生成"],
    ["生成PO表格HTML", "561", "to_table_html", '{"file":"${paths.html_dir}/PO清单.html","title":"采购订单(PO)明细报告"}', "Y", "生成PO交互式表格"],
    ["加载PR数据", "570", "load_step_result", '{"step_id":"PR选择输出列"}', "Y", "加载未转单数据(已选择PR输出列)用于HTML生成"],
    ["生成PR表格HTML", "571", "to_table_html", '{"file":"${paths.html_dir}/PR清单.html","title":"采购申请(PR)明细报告"}', "Y", "生成PR交互式表格"],
    ["【完成】", "0", "print", "{}", "Y", "=== 处理完成 ==="],
    ["显示完成信息", "600", "print", "{}", "Y", "处理完成！输出文件已保存"],
    ["显示缓存配置", "601", "list_dynamic_configs", "{}", "Y", "显示已缓存的配置列表"],
    ["end", "999", "end", "{}", "Y", "结束流程"],
    ["无文件处理", "900", "print", "{}", "Y", "【警告】未找到匹配的purchase*.xlsx文件，请检查：1.目录是否正确 2.文件命名是否符合规范 3.文件是否在60分钟内修改"],
    ["无文件结束", "910", "end", "{}", "Y", "无文件时结束"],
    ["", "1009", "log", "{}", "Y", ""],
    ["", "1019", "log", "{}", "Y", ""],
]

# 写入文件
with open(r'C:\Users\Administrator\Music\elt_purchase.json', 'w', encoding='utf-8') as f:
    json.dump(data, f, ensure_ascii=False, indent=2)

print('JSON文件已重建')
print(f'总步骤数: {len(data)}')
